site_name: Aebel's Notes
theme:
  name: 'material'
  palette:
    primary: black
  logo: assets/icon.png
  favicon: assets/icon.png
  features:
  - content.code.copy
extra_css: [assets/extra.css]
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - assets/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
